language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0782709df8b0_key -iv $encrypted_0782709df8b0_iv
  -in docker-react-test-2d4df9b343d2.json.enc -out .\\docker-react-test-2d4df9b343d2.json
  -d
- docker build -t richtercamden/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true richtercamden/docker-react npm run test
deploy:
  provider: gae
  keyfile: docker-react-test-f4b5448d9562.json
  project: docker-react-test
  on:
    branch: master
